apiVersion: webapp.convect.ai/v1
kind: GuestBook
metadata:
  name: guestbook-sample
spec:
  redisName: redis-sample
  frontend:
    resources:
      requests:
        cpu: 80m
    servingPort: 8080
    replicas: 1
